#person:
#  #lastName: zhangsan
#  age: 24
#  boss: false
#  birthday: 2020/04/18
#  map: {k1: v1, k2: v2}
#  list: [lisi,wangwu,zhaoliu]
#  #list:
#  #  - lisi
#  #  - wangwu
#  #  - zhaoliu
#  dog:
#    name: huahua
#    age: 2
#  last-name: zhangsan

#默认8080,---表示文档块
server:
  port: 8080
spring:
  profiles:
    active: prod
---
server:
  port: 8082
spring:
  profiles: dev
---
server:
  port: 8083
spring:
  profiles: prod
---